NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
  "GCAJ7I4PEGHL5Z5ZQZRACTYSBLVYVZY4IZ4KP4H5ADZ4WMOERPNCV6W2",
  "GBQGWAELHIQSRIAUMDDNN2DLEGWVAD67NHWED6YGZGG57QCPLHQV2KKF"
]

CURRENCIES=[
  {
    code="NJC",
    issuer="GCAJ7I4PEGHL5Z5ZQZRACTYSBLVYVZY4IZ4KP4H5ADZ4WMOERPNCV6W2",
    display_decimals=2,
    name="New Jerusalem Coin",
    desc="The official asset of the New Jerusalem Calendar vision. See https://njc777.com for details.",
    conditions="Issued and distributed on the Stellar Network by New Jerusalem Coin."
  }
]

CONTACT_INFO={
  organization="New Jerusalem Calendar",
  website="https://njc777.com",
  email="contact@njc777.com"
}
